name: Deploy with GitOps

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Write .env from GitHub Secrets
        run: |
          echo "$ENV_FILE_CONTENT" > kustomize/overlays/local/config.env
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}

      - name: Apply Kustomize
        run: |
          cd kustomize/overlays/local
          kustomize build . 