apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: greet-env-config
    envs:
      - configmap.yaml


resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true