apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base

configMapGenerator:
  - name: service-a-config
    envs:
      - config-env.yaml
generatorOptions:
  disableNameSuffixHash: true
