name: GitOps Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: "Deployment environment (local, staging, production)"
        required: true
        default: "local"

  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.deploy_env || 'local' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step riêng cho LOCAL
      - name: Write local config.env
        if: ${{ github.event.inputs.deploy_env == 'local' || github.event.inputs.deploy_env == '' }}
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT_LOCAL }}" > kustomize/overlays/local/config.env

      # Step riêng cho STAGING
      - name: Write staging config.env
        if: ${{ github.event.inputs.deploy_env == 'sandbox' }}
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT_STAGING }}" > kustomize/overlays/sandbox/config.env

      # Step riêng cho PRODUCTION
      - name: Write production config.env
        if: ${{ github.event.inputs.deploy_env == 'production' }}
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT_PRODUCTION }}" > kustomize/overlays/production/config.env

      - name: Build and Apply Kustomize
        run: |
          cd kustomize/overlays/${{ github.event.inputs.deploy_env || 'local' }}
          kustomize build .
