name: GitOps Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: "Deployment environment (local, staging, production)"
        required: true
        default: "local"

  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.deploy_env || 'local' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set ENV_FILE_CONTENT based on deploy_env
        run: |
          echo "$ENV_FILE_CONTENT" > kustomize/overlays/${{ github.event.inputs.deploy_env || 'local' }}/config.env
        env:
          ENV_FILE_CONTENT: ${{ 
            github.event.inputs.deploy_env == 'production' && secrets.ENV_FILE_CONTENT_PRODUCTION ||
            github.event.inputs.deploy_env == 'staging' && secrets.ENV_FILE_CONTENT_STAGING ||
            secrets.ENV_FILE_CONTENT_LOCAL 
          }}

      - name: Build and Apply Kustomize
        run: |
          cd kustomize/overlays/${{ github.event.inputs.deploy_env || 'local' }}
          kustomize build .
